import mongoose, {Schema} from 'mongoose';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';

/**
 * @description creates new user with schema below using username, fullName, email, profession, profile, password
 * @example {
 * username: username123,
 * fullName: Name Caste,
 * email: user@mail.com,
 * profession: "Student",
 * password: user@1234
 * }
 */
const userSchema = new Schema({
    username: {
        type: String,
        unique: true,
        lowercase: true,
        required: [true, "Username is required."],
        trim: true
    },
    fullName: {
        type: String,
        required: [true, "FullName is Required."],
        trim: true
    },
    email: {
        type: String,
        required: [true, "Email is Required."]
    },
    profession: {
        type: String,
        enum: ["Student", "Employee"],
        required: [true, "Profession is required."],
        default: "Student"
    },
    profile: {
        type: String,
        trim: true
    },
    password: {
        type: String,
        required: [true, "Password is Required."]
    }
},{
    timestamps:true
})

//Hashes Password Before Saving Whenever Gets Modified
userSchema.pre("save", async function(){
    if(this.isModified("password")){
        this.password = await bcrypt.hash(this.password, 10);
    }
})

/**
 * @description Generates Cookie for login and register
 * @returns String token generated by jsonwebtoken on the basis of _id and email
 */
userSchema.methods.generateAccessToken = function () {
    return jwt.sign({
        _id: this._id, 
        email: this.email
    }, 
    process.env.TOKEN_SECRET,{
        expiresIn: process.env.EXPIRE_TIME
    }
    )
}

/**
 * 
 * @param {password} password
 * @returns Hashed password
 * @description Method used to check whether the passowrd is correct or not, or can say for password verification
 */
userSchema.methods.isPasswordCorrect = async function (password) {
    return await bcrypt.compare(password, this.password);
}

export const userModel = mongoose.model('USER', userSchema);